### PR TITLE
tweaks for proper graph browser output

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by pjotrp** [comment]
Hi @mr-c, do we still need to merge this? There is some conflict.

**Comment by mr-c** [comment]
Yes, this needs merging. I'm on my phone right now, so I can't fix the `workflow/tools` git submodule conflict. The latest commit from the `release` branch of that repo is how I would resolve the conflict.

**Comment by pjotrp** [comment]
I tried to fix it, but it is a git submodules problem. I don't know which version of the repo we should use.

**Comment by mr-c** [comment]
Whoever gets to this first should update the git submodule to https://github.com/common-workflow-library/bio-cwl-tools/commit/138820b6becc96ed5db637dbb86a7d782a2d64d2

**Comment by LLTommy** [comment]
What is going on with this pull request? It is hanging around and we are getting out of sync and I have no idea what's going on here.

**Comment by mr-c** [comment]
I'll send a new PR

**Comment by mr-c** [comment]
See https://github.com/arvados/bh20-seq-resource/pull/79

**Pull request closed without merging**
